-- ============================================
-- AI Infrastructure Schema with Cost Tracking
-- ============================================

-- Drop existing function if it exists (fixes the error)
DROP FUNCTION IF EXISTS match_framework_chunks(vector, double precision, integer);

-- Enable pgvector extension for embeddings (if not already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================
-- AI PROVIDERS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS ai_providers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  provider_type TEXT NOT NULL, -- 'text', 'image', 'video', 'audio'
  is_active BOOLEAN DEFAULT true,
  api_key_env_var TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- AI MODELS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS ai_models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id UUID REFERENCES ai_providers(id) ON DELETE CASCADE NOT NULL,
  model_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  model_tier TEXT NOT NULL, -- 'fast', 'balanced', 'premium'
  cost_per_1m_input DECIMAL(10, 4),
  cost_per_1m_output DECIMAL(10, 4),
  max_tokens INTEGER,
  supports_streaming BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(provider_id, model_name)
);

-- ============================================
-- AI EXECUTIONS LOG
-- ============================================
CREATE TABLE IF NOT EXISTS ai_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id UUID REFERENCES clients(id) ON DELETE SET NULL,
  model_id UUID REFERENCES ai_models(id) NOT NULL,
  task_type TEXT NOT NULL,
  complexity TEXT,
  input_data JSONB NOT NULL,
  output_data JSONB,
  input_tokens INTEGER,
  output_tokens INTEGER,
  total_cost_usd DECIMAL(10, 6),
  duration_ms INTEGER,
  status TEXT NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_executions_user_id ON ai_executions(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_executions_client_id ON ai_executions(client_id);
CREATE INDEX IF NOT EXISTS idx_ai_executions_model_id ON ai_executions(model_id);
CREATE INDEX IF NOT EXISTS idx_ai_executions_created_at ON ai_executions(created_at);

-- ============================================
-- MARKETING FRAMEWORKS TABLE (For RAG)
-- ============================================
CREATE TABLE IF NOT EXISTS marketing_frameworks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  content TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_marketing_frameworks_user_id ON marketing_frameworks(user_id);
CREATE INDEX IF NOT EXISTS idx_marketing_frameworks_category ON marketing_frameworks(category);

-- ============================================
-- FRAMEWORK CHUNKS TABLE (Vector Embeddings)
-- ============================================
CREATE TABLE IF NOT EXISTS framework_chunks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  framework_id UUID REFERENCES marketing_frameworks(id) ON DELETE CASCADE NOT NULL,
  chunk_index INTEGER NOT NULL,
  content TEXT NOT NULL,
  embedding VECTOR(1536), -- OpenAI text-embedding-3-small dimension
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_framework_chunks_framework_id ON framework_chunks(framework_id);

-- Vector similarity search index (created after pgvector is enabled)
CREATE INDEX IF NOT EXISTS idx_framework_chunks_embedding ON framework_chunks 
USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ============================================
-- RLS POLICIES
-- ============================================

-- AI Providers (public read)
ALTER TABLE ai_providers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can view providers" ON ai_providers;
CREATE POLICY "Anyone can view providers" ON ai_providers FOR SELECT USING (true);

-- AI Models (public read)
ALTER TABLE ai_models ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can view models" ON ai_models;
CREATE POLICY "Anyone can view models" ON ai_models FOR SELECT USING (true);

-- AI Executions (private)
ALTER TABLE ai_executions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own executions" ON ai_executions;
DROP POLICY IF EXISTS "Users can insert their own executions" ON ai_executions;
CREATE POLICY "Users can view their own executions" ON ai_executions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own executions" ON ai_executions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Marketing Frameworks (private)
ALTER TABLE marketing_frameworks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own frameworks" ON marketing_frameworks;
CREATE POLICY "Users can manage their own frameworks" ON marketing_frameworks FOR ALL USING (auth.uid() = user_id);

-- Framework Chunks (private via framework ownership)
ALTER TABLE framework_chunks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can access chunks for their frameworks" ON framework_chunks;
CREATE POLICY "Users can access chunks for their frameworks" ON framework_chunks FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM marketing_frameworks 
    WHERE marketing_frameworks.id = framework_chunks.framework_id 
    AND marketing_frameworks.user_id = auth.uid()
  )
);

-- ============================================
-- VECTOR SIMILARITY SEARCH FUNCTION (FIXED)
-- ============================================

CREATE OR REPLACE FUNCTION match_framework_chunks(
  query_embedding VECTOR(1536),
  match_threshold FLOAT,
  match_count INT
)
RETURNS TABLE (
  id BIGINT,
  framework_id UUID,
  content TEXT,
  similarity FLOAT
)
LANGUAGE SQL STABLE
AS $$
  SELECT
    framework_chunks.id,
    framework_chunks.framework_id,
    framework_chunks.content,
    1 - (framework_chunks.embedding <=> query_embedding) AS similarity
  FROM framework_chunks
  WHERE 1 - (framework_chunks.embedding <=> query_embedding) > match_threshold
  ORDER BY similarity DESC
  LIMIT match_count;
$$;

-- ============================================
-- SEED DATA
-- ============================================

-- Insert AI Providers
INSERT INTO ai_providers (name, display_name, provider_type, api_key_env_var, metadata)
VALUES
  ('claude', 'Anthropic Claude', 'text', 'ANTHROPIC_API_KEY', '{"docs": "https://docs.anthropic.com"}'),
  ('gemini', 'Google Gemini', 'text', 'GOOGLE_AI_API_KEY', '{"docs": "https://ai.google.dev"}')
ON CONFLICT (name) DO NOTHING;

-- Insert AI Models
INSERT INTO ai_models (provider_id, model_name, display_name, model_tier, cost_per_1m_input, cost_per_1m_output, max_tokens, supports_streaming, metadata)
VALUES
  -- Claude models
  ((SELECT id FROM ai_providers WHERE name = 'claude'), 'claude-opus-4-20250514', 'Claude Opus 4', 'premium', 15.00, 75.00, 200000, true, '{"best_for": "Complex reasoning, long documents"}'),
  ((SELECT id FROM ai_providers WHERE name = 'claude'), 'claude-sonnet-4-20250514', 'Claude Sonnet 4', 'balanced', 3.00, 15.00, 200000, true, '{"best_for": "Most tasks, good balance"}'),
  ((SELECT id FROM ai_providers WHERE name = 'claude'), 'claude-haiku-4-20250514', 'Claude Haiku 4', 'fast', 0.25, 1.25, 200000, true, '{"best_for": "Simple tasks, speed"}'),
  
  -- Gemini models
  ((SELECT id FROM ai_providers WHERE name = 'gemini'), 'gemini-2.0-flash-exp', 'Gemini 2.0 Flash', 'fast', 0.00, 0.00, 1000000, true, '{"best_for": "Fast, free tasks"}'),
  ((SELECT id FROM ai_providers WHERE name = 'gemini'), 'gemini-2.5-pro-002', 'Gemini 2.5 Pro', 'balanced', 1.25, 5.00, 2000000, true, '{"best_for": "Complex reasoning, long context"}')
ON CONFLICT (provider_id, model_name) DO NOTHING;

-- ============================================
-- UPDATED_AT TRIGGER
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_marketing_frameworks_updated_at ON marketing_frameworks;
CREATE TRIGGER update_marketing_frameworks_updated_at 
BEFORE UPDATE ON marketing_frameworks
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
